In [2]:
import numpy as np
from numpy import linalg as la
np.random.seed(7)

mat_array = 1*np.random.random_sample((1,3,3))

for i in range(9999):
    tmp_mat = 1*np.random.random_sample((1,3,3))
    if la.matrix_rank(tmp_mat)==3:
        mat_array = np.append(mat_array,tmp_mat,axis=0)
        #print('error')
    else:
        continue

#A = np.matrix([[ele,2,3],[4,5,6],[7,8,9]])
#la.matrix_rank(mat_array[0,:,:])
mat_inv_array=la.inv(mat_array)

In [3]:
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential()
model.add(Dense(32, input_shape=(3,3),activation='relu'))
model.add(Dense(16, activation='tanh'))
model.add(Dense(3, activation='linear'))

model.compile(optimizer='adadelta',
             loss='mean_squared_logarithmic_error',
             metrics=['accuracy'])

X = np.copy(mat_array)
Y = np.copy(mat_inv_array)

model.fit(X, Y, epochs=100)

Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Epoch 1/100
10000/10000 [==============================] - 1s 125us/step - loss: 0.8895 - acc: 0.4443
Epoch 2/100
10000/10000 [==============================] - 1s 117us/step - loss: 0.8679 - acc: 0.4581
Epoch 3/100
10000/10000 [==============================] - 1s 112us/step - loss: 0.8658 - acc: 0.4569
Epoch 4/100
10000/10000 [==============================] - 1s 110us/step - loss: 0.8652 - acc: 0.4594
Epoch 5/100
10000/10000 [==============================] - 3s 255us/step - loss: 0.8647 - acc: 0.4571
Epoch 6/100
10000/10000 [==============================] - 2s 176us/step - loss: 0.8645 - acc: 0.4589
Epoch 7/100
10000/10000 [==============================] - 1s 130us/step - loss: 0.8638 - acc: 0.4588
Epoch 8/100
10000/10000 [==============================] - 1s 146us/step - loss: 0.8637 - acc: 0.4590 0s - loss: 0.8714 - a
Epoch 9/100
10000/10000 [=================

10000/10000 [==============================] - 1s 141us/step - loss: 0.8610 - acc: 0.4581
Epoch 75/100
10000/10000 [==============================] - 2s 203us/step - loss: 0.8611 - acc: 0.4583
Epoch 76/100
10000/10000 [==============================] - 3s 310us/step - loss: 0.8608 - acc: 0.4586
Epoch 77/100
10000/10000 [==============================] - 1s 61us/step - loss: 0.8607 - acc: 0.4585
Epoch 78/100
10000/10000 [==============================] - 2s 172us/step - loss: 0.8611 - acc: 0.4585
Epoch 79/100
10000/10000 [==============================] - 1s 113us/step - loss: 0.8610 - acc: 0.4576
Epoch 80/100
10000/10000 [==============================] - 1s 102us/step - loss: 0.8608 - acc: 0.4579
Epoch 81/100
10000/10000 [==============================] - 1s 52us/step - loss: 0.8608 - acc: 0.4593
Epoch 82/100
10000/10000 [==============================] - 1s 52us/step - loss: 0.8609 - acc: 0.4601
Epoch 83/100
10000/10000 [==============================] - 0s 49us/step - loss: 0.8611 -

In [4]:
test = 100*np.random.random_sample((1,3,3))
pred = model.predict(test)
print(la.inv(test))
print(pred)

[[[ 0.00676518 -0.05567394  0.05415501]
  [ 0.00809765  0.03670199 -0.03932326]
  [-0.00611455  0.00426117  0.01436597]]]
[[[ 0.21826738  0.7343291   1.3147569 ]
  [-0.51918375 -2.4664042  -0.9610343 ]
  [ 0.00571376 -1.3281542  -0.37208453]]]


In [6]:
X.shape
Y.shape

(10000, 3, 3)

In [7]:
Y.shape

(10000, 3, 3)