In [1]:
import numpy as np
from numpy import linalg as la
np.random.seed(7)

mat_array = 1*np.random.random_sample((1,3,3))

for i in range(9999):
    tmp_mat = 1*np.random.random_sample((1,3,3))
    if la.matrix_rank(tmp_mat)==3:
        mat_array = np.append(mat_array,tmp_mat,axis=0)
        #print('error')
    else:
        continue

#A = np.matrix([[ele,2,3],[4,5,6],[7,8,9]])
#la.matrix_rank(mat_array[0,:,:])
mat_inv_array=la.inv(mat_array)

In [2]:
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential()
model.add(Dense(32, input_shape=(3,3),activation='relu'))
model.add(Dense(16, activation='tanh'))
model.add(Dense(3, activation='linear'))

model.compile(optimizer='adadelta',
             loss='mean_squared_logarithmic_error',
             metrics=['accuracy'])

X = np.copy(mat_array)
Y = np.copy(mat_inv_array)

model.fit(X, Y, epochs=100)

Using TensorFlow backend.


Epoch 1/100
10000/10000 [==============================] - 1s 91us/step - loss: 0.8895 - acc: 0.4442
Epoch 2/100
10000/10000 [==============================] - 1s 70us/step - loss: 0.8679 - acc: 0.4579
Epoch 3/100
10000/10000 [==============================] - 0s 47us/step - loss: 0.8658 - acc: 0.4570
Epoch 4/100
10000/10000 [==============================] - 0s 50us/step - loss: 0.8652 - acc: 0.4592
Epoch 5/100
10000/10000 [==============================] - 0s 47us/step - loss: 0.8647 - acc: 0.4574
Epoch 6/100
10000/10000 [==============================] - 0s 48us/step - loss: 0.8645 - acc: 0.4591
Epoch 7/100
10000/10000 [==============================] - 0s 48us/step - loss: 0.8638 - acc: 0.4587: 0s - loss: 0.8697 - acc: 0.4
Epoch 8/100
10000/10000 [==============================] - 0s 49us/step - loss: 0.8638 - acc: 0.4591
Epoch 9/100
10000/10000 [==============================] - 0s 49us/step - loss: 0.8636 - acc: 0.4612
Epoch 10/100
10000/10000 [==============================] - 1

10000/10000 [==============================] - 0s 47us/step - loss: 0.8609 - acc: 0.4579
Epoch 81/100
10000/10000 [==============================] - 0s 47us/step - loss: 0.8608 - acc: 0.4586
Epoch 82/100
10000/10000 [==============================] - 0s 47us/step - loss: 0.8610 - acc: 0.4592
Epoch 83/100
10000/10000 [==============================] - 0s 46us/step - loss: 0.8611 - acc: 0.4585
Epoch 84/100
10000/10000 [==============================] - 0s 46us/step - loss: 0.8609 - acc: 0.4579
Epoch 85/100
10000/10000 [==============================] - 0s 46us/step - loss: 0.8609 - acc: 0.4580
Epoch 86/100
10000/10000 [==============================] - 0s 46us/step - loss: 0.8609 - acc: 0.4580
Epoch 87/100
10000/10000 [==============================] - 0s 46us/step - loss: 0.8609 - acc: 0.4582
Epoch 88/100
10000/10000 [==============================] - 0s 46us/step - loss: 0.8610 - acc: 0.4600
Epoch 89/100
10000/10000 [==============================] - 0s 46us/step - loss: 0.8610 - acc: 

In [4]:
test = 100*np.random.random_sample((1,3,3))
pred = model.predict(test)
print(la.inv(test))
print(pred)

[[[ 0.00676518 -0.05567394  0.05415501]
  [ 0.00809765  0.03670199 -0.03932326]
  [-0.00611455  0.00426117  0.01436597]]]
[[[ 0.21826738  0.7343291   1.3147569 ]
  [-0.51918375 -2.4664042  -0.9610343 ]
  [ 0.00571376 -1.3281542  -0.37208453]]]
